from __future__ import annotations

import json
import math
import re
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass
from typing import Any

from langchain_openai import ChatOpenAI

from agents.state import ResearchState
from shared.config import WRITER_MODEL
from shared.llm_output_validation import (
    validate_conclusion_writer_output,
    validate_section_writer_output,
)
from shared.llm_invoke import invoke_with_backoff, is_token_limit_exceeded
from shared.normalization import extract_json
from shared.yaml_loader import get_system_prompt, get_user_prompt


DISCLAIMER_TEXT = (
    "This report was automatically generated by the Company Deep Research Agent "
    "using publicly available data (yfinance API, Financial Modeling Prep, Alpha Vantage, "
    "SEC EDGAR, Tavily News Search). All data reflects information available as of the "
    "report date. This document does not constitute investment advice or a solicitation "
    "to trade any security. Consult a qualified financial advisor before making investment "
    "decisions."
)


@dataclass(frozen=True)
class SectionSpec:
    id: str
    title: str
    prompt_filename: str
    min_words: int
    required_paragraphs: int
    required_source_types: list[str]


SECTION_SPECS: list[SectionSpec] = [
    SectionSpec(
        id="3.1",
        title="Company Overview & Business Structure",
        prompt_filename="section_writer_3_1.yaml",
        min_words=150,
        required_paragraphs=2,
        required_source_types=["api", "sec"],
    ),
    SectionSpec(
        id="4.1a",
        title="Revenue & Profitability",
        prompt_filename="section_writer_4_1a.yaml",
        min_words=200,
        required_paragraphs=3,
        required_source_types=["api", "sec"],
    ),
    SectionSpec(
        id="4.1b",
        title="Earnings Quality & Cash Flow",
        prompt_filename="section_writer_4_1b.yaml",
        min_words=180,
        required_paragraphs=2,
        required_source_types=["api", "sec"],
    ),
    SectionSpec(
        id="4.1c",
        title="Balance Sheet & Financial Stability",
        prompt_filename="section_writer_4_1c.yaml",
        min_words=150,
        required_paragraphs=2,
        required_source_types=["api", "sec"],
    ),
    SectionSpec(
        id="4.2",
        title="Valuation Analysis",
        prompt_filename="section_writer_4_2.yaml",
        min_words=180,
        required_paragraphs=3,
        required_source_types=["api"],
    ),
    SectionSpec(
        id="4.3",
        title="Catalysts & Risk Factors",
        prompt_filename="section_writer_4_3.yaml",
        min_words=150,
        required_paragraphs=2,
        required_source_types=["sec", "news"],
    ),
    SectionSpec(
        id="4.4",
        title="Industry & Competitive Landscape",
        prompt_filename="section_writer_4_4.yaml",
        min_words=120,
        required_paragraphs=2,
        required_source_types=["api"],
    ),
    SectionSpec(
        id="4.5",
        title="News Sentiment & Market Perception",
        prompt_filename="section_writer_4_5.yaml",
        min_words=120,
        required_paragraphs=2,
        required_source_types=["news", "api"],
    ),
]


def _word_count(text: str) -> int:
    return len(re.findall(r"\b[\w']+\b", text or ""))


def _contains_prohibited_language(paragraphs: list[str]) -> list[str]:
    joined = "\n".join(paragraphs or [])
    problems: list[str] = []
    forbidden_phrases = [
        "It is worth noting that",
        "Needless to say",
        "It should be mentioned",
    ]
    for phrase in forbidden_phrases:
        if phrase in joined:
            problems.append(f"forbidden_phrase:{phrase}")

    if "•" in joined:
        problems.append("contains_bullet_char")
    if re.search(r"(^|\n)\s*[-*]\s+\S", joined):
        problems.append("looks_like_bullets")

    if "—" in joined or "–" in joined:
        problems.append("contains_em_dash")
    return problems


def _unwrap_nested_section(raw: dict[str, Any], spec_id: str) -> dict[str, Any]:
    """
    LLM이 body_paragraphs를 중첩 키로 감싸서 반환할 때 unwrap합니다.
    예: {"4.2": {"valuation_analysis": {"body_paragraphs": [...]}}}
         → {"body_paragraphs": [...], "sources": [...]}
    body_paragraphs가 이미 있으면 그대로 반환합니다.
    """
    if "body_paragraphs" in raw:
        return raw

    # 1단계: spec_id 키 직접 시도 (예: "4.2")
    candidate = raw.get(spec_id)
    if isinstance(candidate, dict):
        if "body_paragraphs" in candidate:
            return candidate
        # 한 단계 더 안쪽 (예: {"valuation_analysis": {...}})
        if len(candidate) == 1:
            inner = next(iter(candidate.values()))
            if isinstance(inner, dict) and "body_paragraphs" in inner:
                return inner

    # 2단계: 단일 키 dict unwrap
    if len(raw) >= 1:
        for val in raw.values():
            if isinstance(val, dict):
                if "body_paragraphs" in val:
                    return val
                # 두 단계 중첩
                if len(val) == 1:
                    inner = next(iter(val.values()))
                    if isinstance(inner, dict) and "body_paragraphs" in inner:
                        return inner

    return raw


def _validate_section(section: dict[str, Any], spec: SectionSpec) -> list[str]:
    errors: list[str] = []
    if not isinstance(section, dict):
        return ["section_not_object"]

    if section.get("id") != spec.id:
        errors.append(f"section_id_mismatch:{section.get('id')}!= {spec.id}")

    paragraphs = section.get("body_paragraphs")
    if not isinstance(paragraphs, list):
        errors.append("body_paragraphs_not_list")
        paragraphs = []
    else:
        normalized: list[str] = []
        for p in paragraphs:
            if isinstance(p, str):
                normalized.append(p.replace("—", "; ").replace("–", "-"))
            else:
                normalized.append(p)
        section["body_paragraphs"] = normalized
        paragraphs = normalized

    if len(paragraphs) != spec.required_paragraphs:
        errors.append(f"paragraph_count_mismatch:{len(paragraphs)}!= {spec.required_paragraphs}")

    total_words = sum(_word_count(p) for p in paragraphs)
    if total_words < spec.min_words:
        errors.append(f"word_count_below_min:{total_words}<{spec.min_words}")

    # Analyst report quality checks
    # [최적화] 데이터가 없을 때 LLM이 솔직하게 "Data unavailable"이라고 답변한 것을 에러로 처리하지 않도록 주석 처리.
    # 이를 통해 억지로 지어내거나 의미 없는 재시도(Retry) 루프를 도는 비효율을 방지합니다.
    # for i, p in enumerate(paragraphs):
    #     if isinstance(p, str) and "data unavailable" in p.lower():
    #         errors.append(f"placeholder_text_in_paragraph:{i}")

    errors.extend(_contains_prohibited_language(paragraphs))

    return errors


def _extract_checklist_item(checklist_output: dict[str, Any], item_id: str) -> dict[str, Any] | None:
    checklist_payload = (checklist_output or {}).get("payload", {}).get("checklist", {}) or {}
    for _cat_key, cat_val in checklist_payload.items():
        items = (cat_val or {}).get("items") or []
        for item in items:
            if item.get("id") == item_id:
                return item
    return None


def _build_key_financials_table(checklist_output: dict[str, Any], researcher_output: dict[str, Any]) -> list[dict[str, Any]]:
    metrics = [
        ("A1", "Revenue Growth (YoY)"),
        ("A2", "Operating Margin"),
        ("A3", "EPS vs. Consensus"),
        ("A4", "Debt Ratio Trend"),
        ("A5", "Free Cash Flow (FCF)"),
    ]

    # Pull actual data from researcher_output to fill the 'change' column
    financial_payload = (researcher_output or {}).get("payload", {}).get("financial", {})
    yoy_val = financial_payload.get("revenue_yoy_pct")

    table: list[dict[str, Any]] = []
    for item_id, label in metrics:
        item = _extract_checklist_item(checklist_output, item_id) or {}
        verdict = item.get("verdict")
        
        table.append({
            "metric": label,
            "value": item.get("value"),
            "change": f"{yoy_val}%" if (item_id == "A1" and yoy_val is not None) else "Data unavailable",
            "verdict": verdict,
            "source_type": "api" if verdict != "insufficient_data" else None,
        })
    return table


def _slice_checklist_output_for_section(checklist_output: dict[str, Any], section_id: str) -> dict[str, Any]:
    payload = (checklist_output or {}).get("payload", {}) or {}
    checklist = payload.get("checklist") or {}

    needed_item_ids: set[str] = set()
    if section_id == "4.1a": needed_item_ids = {"A1", "A2"}
    elif section_id == "4.1b": needed_item_ids = {"A3", "A5"}
    elif section_id == "4.1c": needed_item_ids = {"A4"}
    elif section_id == "4.2": needed_item_ids = {"B1", "B2", "B3", "B4", "B5", "B6"}
    elif section_id == "4.3": needed_item_ids = {"C1", "C2", "C3"}
    elif section_id == "4.4": needed_item_ids = {"D1", "D2", "D3"}
    elif section_id == "4.5": needed_item_ids = {"E1", "E2"}

    sliced_checklist: dict[str, Any] = {}
    for cat_key, cat_val in checklist.items():
        items = cat_val.get("items") or []
        new_items = [it for it in items if it.get("id") in needed_item_ids]
        if new_items:
            sliced_checklist[cat_key] = {**cat_val, "items": new_items}

    return {
        "run_id": payload.get("run_id"),
        "ticker": payload.get("ticker"),
        "report_date": payload.get("report_date"),
        "current_price": payload.get("current_price"),
        "checklist": sliced_checklist,
        "summary": payload.get("summary"),
    }


def _call_section_llm(*, llm: ChatOpenAI, prompt_filename: str, context: dict[str, Any], researcher_output_json: str, checklist_output_json: str, validation_feedback: str | None = None):
    system = get_system_prompt(prompt_filename)
    user = get_user_prompt(prompt_filename, **context, researcher_output_json=researcher_output_json, checklist_output_json=checklist_output_json)
    
    user += "\n\nCRITICAL: Return ONLY valid JSON. Output the JSON, then output the exact token: </json_end>"
    user += "\n\nTONE INSTRUCTION: Write like a top-tier Wall Street equity research analyst. NEVER use robotic phrases like 'Data unavailable' in the text. If a specific metric is missing, discuss the broader fundamental trend or omit the metric gracefully. Maintain a highly professional, objective, and analytical tone."
    user += "\n\nSOURCE CITATION RULE: Do NOT embed source references inside body_paragraphs text (no '[sources: ...]' or '[Source: ...]' inline). Sources belong ONLY in the sources[] array. body_paragraphs must read as clean, professional prose with no citation markers."
    
    response = invoke_with_backoff(
        llm,
        [{"role": "system", "content": system}, {"role": "user", "content": user}],
        stop=["</json_end>"]
    )
    return extract_json(response.content)


def _write_section_with_retry(*, llm: ChatOpenAI, spec: SectionSpec, state: ResearchState, researcher_output: dict[str, Any], checklist_output: dict[str, Any], max_attempts: int = 3) -> dict[str, Any]:
    context = {
        "ticker": state["ticker"], "company_name": state["company_name"], "report_date": state["report_date"],
        "run_id": state["run_id"], "exchange": "NASDAQ", "sector": state.get("sector", "Technology"),
        "sector_avg_pe": state.get("sector_avg_pe", 25), "current_price": state.get("current_price") or "Data unavailable",
    }

    sliced_checklist = _slice_checklist_output_for_section(checklist_output, spec.id)
    researcher_json = json.dumps(researcher_output, ensure_ascii=False, default=str)
    checklist_json = json.dumps(sliced_checklist, ensure_ascii=False, default=str)

    section: dict[str, Any] = {}
    last_errors: list[str] = []
    for attempt in range(1, max_attempts + 1):
        try:
            raw = _call_section_llm(llm=llm, prompt_filename=spec.prompt_filename, context=context, researcher_output_json=researcher_json, checklist_output_json=checklist_json, validation_feedback="\n".join(last_errors) if last_errors else None)
            section = raw.get("section") or raw
            section = _unwrap_nested_section(section, spec.id)
            # Ensure id and title are always present (LLM sometimes omits them).
            section.setdefault("id", spec.id)
            section.setdefault("title", spec.title)
            errors = _validate_section(section, spec)
            if not errors: return section
            last_errors = errors
        except Exception as e:
            # 토큰 초과 시: researcher_json을 30% 줄여 재시도 (open_deep_research 패턴)
            if is_token_limit_exceeded(e) and len(researcher_json) > 500:
                researcher_json = researcher_json[:int(len(researcher_json) * 0.7)]
                last_errors = [f"token_limit_exceeded(attempt={attempt}): truncated researcher_json to {len(researcher_json)} chars"]
            else:
                last_errors = [str(e)]
    # Always guarantee id/title even when all retries fail.
    section.setdefault("id", spec.id)
    section.setdefault("title", spec.title)
    return section


def _write_conclusion_with_retry(*, llm: ChatOpenAI, state: ResearchState, researcher_output: dict[str, Any], checklist_output: dict[str, Any], max_attempts: int = 3) -> dict[str, Any]:
    context = {
        "ticker": state["ticker"], "company_name": state["company_name"], "report_date": state["report_date"],
        "run_id": state["run_id"], "exchange": "NASDAQ", "sector": state.get("sector", "Technology"),
        "sector_avg_pe": state.get("sector_avg_pe", 25),
        "current_price": state.get("current_price") or "Data unavailable",
    }
    
    researcher_json = json.dumps(researcher_output, ensure_ascii=False, default=str)
    checklist_json = json.dumps(checklist_output, ensure_ascii=False, default=str)

    for attempt in range(1, max_attempts + 1):
        try:
            raw = _call_section_llm(llm=llm, prompt_filename="conclusion_writer.yaml", context=context, researcher_output_json=researcher_json, checklist_output_json=checklist_json)
            return raw.get("conclusion") or raw
        except:
            continue
    return {}


def _assemble_report_output(*, state: ResearchState, researcher_output: dict[str, Any], checklist_output: dict[str, Any], sections: list[dict[str, Any]], conclusion: dict[str, Any]) -> dict[str, Any]:
    # HARD SYNC: Force the conclusion to match the auditor's rating
    summary = (checklist_output or {}).get("payload", {}).get("summary", {}) or {}
    rating = summary.get("investment_rating")
    target = summary.get("target_price")

    title_block = {
        "company_name": state["company_name"], "ticker": state["ticker"], "exchange": "NASDAQ",
        "sector": state.get("sector", "Technology"), "report_date": state["report_date"],
        "investment_rating": rating, "target_price_12m": target,
        "current_price": summary.get("current_price"), "upside_pct": summary.get("upside_pct"),
    }

    return {
        "run_id": state["run_id"], "agent": "report_writer", "schema_version": 2, "ticker": state["ticker"], "report_date": state["report_date"],
        "payload": {
            "title_block": title_block,
            "checklist_summary": {},
            "key_financials_table": _build_key_financials_table(checklist_output, researcher_output),
            "sections": sections,
            "conclusion": {
                "investment_rating": rating, # Forced
                "target_price_12m": target,
                "body_paragraphs": conclusion.get("body_paragraphs") or [],
                "bull_case": conclusion.get("bull_case"), "bear_case": conclusion.get("bear_case"),
                "position_strategy": conclusion.get("position_strategy"), "sources": conclusion.get("sources") or [],
            },
        },
        "disclaimer": DISCLAIMER_TEXT,
    }


def build_final_report(state: ResearchState) -> dict[str, Any]:
    researcher_output = state["researcher_output"]
    checklist_output = state["checklist_output"]
    llm = ChatOpenAI(model=WRITER_MODEL, temperature=0.2)

    # ThreadPoolExecutor로 8개 섹션 + 결론을 병렬 실행합니다.
    # (open_deep_research의 asyncio.gather 패턴을 동기 코드에 맞게 적용)
    # OpenAI 클라이언트는 thread-safe하므로 llm 인스턴스 공유 가능합니다.
    print(f"  [report_sections] {len(SECTION_SPECS)}개 섹션 + 결론 병렬 작성 시작...")
    with ThreadPoolExecutor(max_workers=len(SECTION_SPECS) + 1) as executor:
        section_futures = [
            executor.submit(
                _write_section_with_retry,
                llm=llm, spec=s, state=state,
                researcher_output=researcher_output,
                checklist_output=checklist_output,
            )
            for s in SECTION_SPECS
        ]
        conclusion_future = executor.submit(
            _write_conclusion_with_retry,
            llm=llm, state=state,
            researcher_output=researcher_output,
            checklist_output=checklist_output,
        )
        # SECTION_SPECS 순서를 보장하여 결과 수집
        drafted_sections = [f.result() for f in section_futures]
        conclusion = conclusion_future.result()

    return _assemble_report_output(state=state, researcher_output=researcher_output, checklist_output=checklist_output, sections=drafted_sections, conclusion=conclusion)